### ISSUE TITLE
The meaning of reward function

### ISSUE THREAD

**Issue by VickyCas** [JewelryForge/teacher-student#2]
Hello, JewelryForge，thank you for making your work public. 
I don't understand well the settings of reward function? What is the meaning of tanh_reverse，exp_m2_reshape and quadratic_linear_reshape? What is the meaning of each reward function？
Thank you for your answer.

**Comment by chengruiz** [comment]
I'm sorry that my work is not complete right now and may have severe bugs, so it's not suggested to use it as your baseline.
All reshaping functions are used to map torques, velocities, etc. to a (bounded) range, e.g. $[0, 1]$.

**Comment by VickyCas** [comment]
Thank you for your answer! Your work is excellent and meaningful. I'm curious about what some parameters mean, such as forward and lateral of the LinearVelocityReward class in reward.py. Meanwhile, why do you set forward to 0.8 and lateral to 0.4?

**Comment by chengruiz** [comment]
Quadruped robots usually have more capability of moving forward than laterally, so different desired velocities are set.
